### PR TITLE
Bump copyrights to 2020; apply new zproject templates to CI files and build recipes

### PR DESCRIPTION
**Pull request by jimklimov**

### CODE REVIEW

**Comment by jeffdegott** [comment]
@jimklimov Jim, there is some conflicting files here, since the latest merge. Have a look.

**Comment by aquette** [comment]
closing in favor of #121 and the preliminary updates that were done in between

**Comment by jimklimov** [comment]
Re-applied the improvements/fixes brought by this PR over the recently updated upstream/master and re-opened

**Comment by jimklimov** [comment]
Note: this is done with a slightly newer zproject than generally per https://github.com/42ity/zproject/pull/3 and includes its brought-in differences in a separate commit "Regen zproject: apply newer self-test templates from upstream" to show what the extended self-test makefile targets look like. Should not hurt to have them defined here.

**Pull request merged**
